version: 1
formatters:
  simple:
    format: "%(asctime)s; %(levelname)s %(name)s: %(message)s"
    datefmt: ""
handlers:
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: simple
  file_handler:
    class: logging.FileHandler
    filename: application.log
    level: DEBUG
    formatter: simple
loggers:
  werkzeug:
    level: DEBUG
    propagate: True
    handlers:
      - file_handler

root:
  level: DEBUG
  handlers:
    - stream_handler